Repository prgrms-fe-devcourse/FEDC3_UnsungHero_Donggeun, pull requests merged in 2023-01, with the labels that each got.

#5 Feature/comment: 댓글 생성 및 목록 출력
  src/comment/.keep
  src/comment/index.tsx
Labels: 신규 기능

#8 Feature/search: 검색창 및 특정 채널 포스트 목록 출력
  package-lock.json
  package.json
  src/post/index.tsx
  src/search/.keep
  src/search/Index.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
  yarn.lock
Labels: 피드백 요청, 신규 기능

#4 Feature/auth: 회원가입 및 로그인 구현
  .eslintrc.json
  .prettierrc.json
  package.json
  src/auth/Login.tsx
  src/auth/Logout.tsx
  src/auth/SignUp.tsx
  src/auth/index.tsx
  src/auth/useLocalStorage.ts
  yarn.lock
Labels: 피드백 요청, 🔥 매운맛, 신규 기능

#6 Feature/layout: 전체 레이아웃 구조 구현
  src/Router.tsx
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/index.tsx
Labels: 신규 기능, 스타일

#11 Feature/post: 포스트 생성,수정,삭제 구현
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
Labels: 피드백 요청, 신규 기능

#14 Feature/user: 유저 정보 페이지 구현
  package.json
  src/Router.tsx
  src/user/.keep
  src/user/UserPostListItem.tsx
  src/user/index.tsx
  yarn.lock
Labels: 신규 기능

#24 Feature/type-definition: 모델 관련 타입 정의
  src/auth/.kepp
  src/post/.keep
  src/types/channel.ts
  src/types/comment.ts
  src/types/conversation.ts
  src/types/follow.ts
  src/types/like.ts
  src/types/message.ts
  src/types/notification.ts
  src/types/post.ts
  src/types/user.ts
Labels: 신규 기능

#29 Feature/search: 페이지네이션 및 검색어 하이라이팅 기능 구현
  src/search/Index.tsx
  src/search/Pagination.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
Labels: 피드백 요청, 💧 순한맛, 🔥 매운맛, 신규 기능

#33 Feature/follow: 유저 팔로우 & 팔로우 취소 기능 구현
  src/follow/index.tsx
  yarn.lock
Labels: 피드백 요청, 신규 기능

#32 Feature/userpagination: 내가 쓴 글 페이지네이션 구현
  src/user/Pagination.tsx
  src/user/index.tsx
Labels: 신규 기능

#37 Feature/like: 좋아요 기능 구현
  src/api/useMutation.ts
  src/comment/index.tsx
  src/like/.keep
  src/like/index.tsx
  src/post/index.tsx
Labels: 신규 기능, 리팩토링, 버그 수정

#31 Feature/alarm: 알람 관련 기능 구현
  src/alarm/AlarmList.tsx
  src/alarm/AlarmListItem.tsx
  src/alarm/useProduceAlram.ts
Labels: 피드백 요청, 🔥 매운맛, 신규 기능

#45 refactor/notifications: notification 1차 리팩토링
  src/alarm/AlarmList.tsx
  src/alarm/useProduceAlram.ts
  src/notification/.keep
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/ProduceNotification.tsx
  src/types/notification.ts
Labels: 피드백 요청, 🔥 매운맛, 리팩토링, 버그 수정

#48 Feature/post detail: 포스트 화면에 댓글과 좋아요를 연동시킴.
  src/Router.tsx
  src/api/useMutation.ts
  src/comment/index.tsx
  src/like/index.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/post/index.tsx
Labels: 피드백 요청, 리팩토링

#41 Feature/auth: Context API를 통한 전역 상태 관리 기능 구현
  src/auth/Login.tsx
  src/auth/Logout.tsx
  src/auth/SignUp.tsx
  src/contexts/TokenProvider.tsx
  src/types/auth.ts
  src/types/token.ts
Labels: 피드백 요청, 🔥 매운맛, 신규 기능

#43 refactor: 🔨특정 채널 선택시 포스트 목록 보여주기 및 타 채널 선택시 검색창, 검색옵션, 정렬버튼, 페이지네이션 초기화
  src/layout/Channels.tsx
  src/layout/index.tsx
  src/search/Index.tsx
  src/search/Pagination.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
  src/search/isJsonString.tsx
Labels: 피드백 요청, 💧 순한맛, 리팩토링

#46 Feature/userImg: 프로필 이미지, 커버 이미지 수정 기능 구현
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/index.tsx
Labels: 신규 기능

#54 Fix/userinfo: 유저 정보페이지 페이지네이션 오류 수정
  src/Router.tsx
  src/user/Pagination.tsx
  src/user/index.tsx
Labels: 버그 수정

#57 Feature/user infofollow: 팔로잉, 팔로우 목록 확인 기능
  src/Router.tsx
  src/user/Pagination.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/UserPostListItem.tsx
  src/user/UserPosts.tsx
  src/user/index.tsx
Labels: 신규 기능

#55 refactor/auth auth 관련 1차 리팩토링
  src/auth/Login.tsx
  src/auth/SignUp.tsx
Labels: 피드백 요청, 🔥 매운맛, 리팩토링, 버그 수정

#62 Feature/search: 특정 채널 포스트 리스트 라우터 연결 및 메인 페이지 검색 기능 추가
  src/Router.tsx
  src/layout/Channels.tsx
  src/layout/index.tsx
  src/post/index.tsx
  src/search/Index.tsx
  src/search/Pagination.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
Labels: 피드백 요청, 리팩토링, 버그 수정

#64 refactor/context: 로그인을 해야만 token context 사용 가능
  src/contexts/TokenProvider.tsx
  src/types/token.ts
Labels: 피드백 요청, 🔥 매운맛, 리팩토링, 버그 수정

#63 Feature/notifications: 알람 관련 추가 기능 구현
  src/contexts/NotificationStatusProvider.tsx
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/NotificationStatus.tsx
  src/types/notification.ts
Labels: 피드백 요청, 🔥 매운맛, 신규 기능, 리팩토링, 버그 수정

#66 Refactor/user: userId 전역 설정 및 팔로우 버튼 추가
  src/auth/Login.tsx
  src/auth/Logout.tsx
  src/contexts/TokenProvider.tsx
  src/layout/Header.tsx
  src/types/useId.ts
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/index.tsx
Labels: 신규 기능, 리팩토링

#69 feat: ✨글 작성중 새로고침을 눌러도 내용이 유지됨.
  src/App.tsx
  src/post/CreatePost.tsx
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 신규 기능

#78 Feature/search: 메인 페이지 및 각 채널 상단 최다 공감 포스트 리스트 구현
  src/search/Index.tsx
  src/search/MostLikesPosts.tsx
  src/search/Pagination.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
Labels: 피드백 요청, 신규 기능, 리팩토링

#72 Refactor/post add to channel: '채널 글 목록에 글 생성 버튼 추가하고 해당 채널에 글이 생기도록 하기' 외 몇 가지 수정사항
  src/Router.tsx
  src/layout/Header.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/post/index.tsx
  src/search/Index.tsx
Labels: 피드백 요청, 리팩토링

#74 Refactor/add logout: 헤더에 로그아웃 추가.
  src/App.tsx
  src/layout/Header.tsx
Labels: 피드백 요청, 리팩토링

#85 Style/common: 전체 레이아웃 디자인 재설정
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/index.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 스타일

#84 Feature/add image to post: 포스트에 이미지 기능 추가.
  src/layout/Header.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/search/PostList.tsx
Labels: 피드백 요청, 신규 기능

#81 Feature/follow user: 팔로우, 언팔 기능 붙이기
  src/Router.tsx
  src/follow/index.tsx
  src/follow/useFollow.tsx
  src/layout/Header.tsx
  src/types/user.ts
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/index.tsx
Labels: 리팩토링, 버그 수정

#90 Feature/common component: 공통 컴포넌트 생성
  src/common/Avatar.tsx
  src/common/Button.tsx
  src/common/Pagination.tsx
  src/common/index.ts
  src/search/Pagination.tsx
  src/search/PostListContainer.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/UserPosts.tsx
  src/user/index.tsx
Labels: 신규 기능, 리팩토링, 스타일

#58 Feature/suspense: suspense 추가 및 Comment, Like 컴포넌트 리팩토링
  src/api/Error.tsx
  src/api/ErrorBoundary.tsx
  src/api/Loading.tsx
  src/api/request.ts
  src/api/useMutation.ts
  src/comment/api.ts
  src/comment/index.tsx
  src/comment/tempData.ts
  src/contexts/TokenProvider.tsx
  src/like/api.ts
  src/like/index.tsx
  src/post/DetailPost.tsx
Labels: 신규 기능, 리팩토링, 버그 수정

#95 Feature/search: 포스트 리스트 및 검색창 디자인
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
Labels: 피드백 요청, 스타일

#92 Style/auth auth 관련 디자인
  package.json
  src/Router.tsx
  src/auth/Header.tsx
  src/auth/Login.tsx
  src/auth/SignUp.tsx
  src/layout/index.tsx
  yarn.lock
Labels: 피드백 요청, 스타일

#98 Style/notifications notification 추가 기능 및 디자인
  src/App.tsx
  src/comment/api.ts
  src/comment/index.tsx
  src/common/Button.tsx
  src/follow/useFollow.tsx
  src/like/api.ts
  src/like/index.tsx
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/ProduceNotification.tsx
  src/post/DetailPost.tsx
Labels: 피드백 요청, 신규 기능, 스타일

#100 Fix/post fetch: 댓글과 좋아요의 반영이 실시간으로 이루어지게함.
  src/comment/index.tsx
  src/like/index.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/search/PostListContainer.tsx
Labels: 피드백 요청, 버그 수정

#103 feat: :sparkle 404 페이지 추가
  src/NotFound.tsx
  src/Router.tsx
Labels: 피드백 요청, 신규 기능

#106 Style/user: 유저 관련 페이지 및 공통 컴포넌트 스타일 적용
  src/common/Avatar.tsx
  src/common/Button.tsx
  src/common/Pagination.tsx
  src/follow/useFollow.tsx
  src/layout/Header.tsx
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/UserPostListItem.tsx
  src/user/index.tsx
Labels: 스타일

#107 Feature/search: CSS 리팩토링 및 특정 포스트 클릭시 로그인 여부 확인 로직 구현
  src/api/Loading.tsx
  src/search/Index.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
Labels: 피드백 요청, 리팩토링, 스타일

#104 Feature/post update access: 글 작성자 본인이 아닐 시 글 수정 페이지로 접근하지 못하게함(간단 수정)
  src/comment/index.tsx
  src/post/DetailPost.tsx
Labels: 피드백 요청, 신규 기능

#110 Feature/search: 채널 선택시 특정 채널의 포스트 리스트와 연결 및 페이지네이션 일부 수정
  src/common/Button.tsx
  src/common/Pagination.tsx
  src/layout/index.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
Labels: 리팩토링

#108 feat: ✨UpdatePost에서 이미지를 변경하고 미리 볼 수 있음.
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 신규 기능

#113 feature/search: 불필요한 코드 삭제
  src/comment/index.tsx
Labels: 버그 수정

#119 Feature/search: 각 포스터에 해당하는 채널 정보 보여주기 및 글 작성하기 버튼 스타일 적용
  src/post/DetailPost.tsx
  src/search/Index.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
Labels: 리팩토링, 스타일

#121 Style/total layout : 전체 레이아웃 스타일 수정
  public/favicon.ico
  public/index.html
  public/logo.png
  src/api/Loading.tsx
  src/api/apiAddress.ts
  src/auth/Header.tsx
  src/auth/Login.tsx
  src/auth/Logout.tsx
  src/auth/SignUp.tsx
  src/auth/api.ts
  src/comment/api.ts
  src/comment/index.tsx
  src/common/Button.tsx
  src/follow/useFollow.tsx
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/index.tsx
  src/like/api.ts
  src/like/index.tsx
  src/notification/.keep
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/NotificationStatus.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/post/index.tsx
  src/search/Index.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/UserPostListItem.tsx
  src/user/index.tsx
Labels: 스타일

#116 refactor/notification: 알람페이지 페이지네이션 수정
  src/notification/NotificationList.tsx
Labels: 피드백 요청, 스타일

#125 fix: 🚑포스트 수정 화면에서 이미지가 보이지 않던 문제 해결.
  src/post/CreatePost.tsx
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 버그 수정

#128 fix: 🚑작성자가 아니더라도 글 수정 버튼이 보이던 문제 해결.
  src/post/DetailPost.tsx
Labels: 피드백 요청, 버그 수정

#132 feat: ✨댓글에서 유저 아바타를 클릭시 해당 유저 정보 페이지로 이동.
  src/comment/api.ts
  src/comment/index.tsx
  src/comment/tempData.ts
  src/like/api.ts
Labels: 피드백 요청, 신규 기능

#130 feature/search: 포스트 경과시간 표시 기능 구현
  src/search/Index.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
Labels: 피드백 요청, 신규 기능

#136 Feature/user edit confirm: 유저정보페이지 중복확인 추가 및 전반적인 디자인 수정
  src/api/Loading.tsx
  src/auth/Header.tsx
  src/auth/SignUp.tsx
  src/auth/useOverlapConfirm.ts
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
  src/styles/globalStyle.ts
  src/user/UserEdit.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/index.tsx
Labels: 신규 기능, 스타일

#135 Feature/all react-query 작업
  package.json
  src/follow/useFollow.tsx
  src/index.tsx
  src/layout/Channels.tsx
  src/notification/NotificationList.tsx
  src/notification/NotificationStatus.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/search/Index.tsx
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/index.tsx
  yarn.lock
Labels: 리팩토링, 버그 수정

#139 feature/search: 404Error 페이지 이미지 변경 및 메인 페이지 이동 버튼 추가
  src/NotFound.tsx
  src/search/PostList.tsx
Labels: 신규 기능, 스타일

#140 feature/all: react-query stale time 수정
  src/follow/useFollow.tsx
  src/post/DetailPost.tsx
  src/search/Index.tsx
Labels: 리팩토링, 버그 수정

#146 feat: ✨에러페이지 적용
  src/api/Error.tsx
Labels: 피드백 요청, 신규 기능

#144 Fix/create post: 제목 필수 입력, 작성 중 글이 있으면 유저에게 확인 후 불러옴.
  src/post/CreatePost.tsx
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 신규 기능

#145 refactor/notification notification 디자인 및 버그 해결
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/NotificationStatus.tsx
  src/post/DetailPost.tsx
Labels: 피드백 요청, 스타일, 버그 수정

#149 refactor: 🔨PostList 채널 표기 로직 변경.
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
Labels: 피드백 요청, 리팩토링

#148 Refactor/post img: 스켈레톤 추가, 팔로우 목록 페이지 버그 수정, 글꼴 추가
  public/font/BMHANNAPro.ttf
  public/font/NanumBarunGothic.ttf
  src/Router.tsx
  src/Scroll.ts
  src/common/Skeleton.tsx
  src/follow/useFollow.tsx
  src/font/BMHANNAPro.ttf
  src/font/GmarketSansMedium.otf
  src/layout/index.tsx
  src/post/DetailPost.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/styles/font.d.ts
  src/styles/globalStyle.ts
  src/user/index.tsx
Labels: 리팩토링, 스타일, 버그 수정

#150 Refactor/post img: 알림 null 예외처리 추가, 전체 디자인 수정
  src/api/Error.tsx
  src/comment/index.tsx
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/index.tsx
  src/notification/NotificationListItem.tsx
  src/search/PostList.tsx
  src/styles/globalStyle.ts
  src/user/index.tsx
Labels: 리팩토링, 스타일, 버그 수정

#152 design: 💄포스트 상세 페이지 hieght 설정 및 줄간격 설정
  src/post/CreatePost.tsx
  src/post/DetailPost.tsx
Labels: 스타일

#151 fix: 🚑로그인 하지 않으면 글 작성불가.
  src/post/UpdatePost.tsx
  src/search/PostListContainer.tsx
Labels: 신규 기능

#154 fix: 🔨 테스트 채널이 표기되지 않도록함.
  src/layout/Channels.tsx
  src/post/DetailPost.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostListContainer.tsx
Labels: 피드백 요청, 리팩토링

#160 Refactor/skeleton: 스켈레톤 위치 수정, 회원가입&로그인 placeholder 추가
  src/auth/Login.tsx
  src/auth/SignUp.tsx
  src/common/Pagination.tsx
  src/common/Skeleton.tsx
  src/post/DetailPost.tsx
  src/post/UpdatePost.tsx
  src/user/index.tsx
Labels: 리팩토링, 스타일

#162 fix: 🚑내용 수정 시 이전 글의 사진이 나오던 문제 해결.
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 버그 수정

#159 feat:✨ 파일 업로드, 업데이트 시 사진의 용량을 제한함.
  src/api/constValue.ts
  src/post/CreatePost.tsx
  src/post/UpdatePost.tsx
Labels: 피드백 요청, 신규 기능

#161 reafactor/all: 함수명 수정, 공통 hook 모으기, any type 수정
  src/Router.tsx
  src/auth/Login.tsx
  src/auth/Logout.tsx
  src/auth/SignUp.tsx
  src/common/Button.tsx
  src/common/Scroll.ts
  src/contexts/NotificationStatusProvider.tsx
  src/contexts/TokenProvider.tsx
  src/hooks/useFollow.tsx
  src/hooks/useLocalStorage.ts
  src/hooks/useOverlapConfirm.ts
  src/layout/Header.tsx
  src/notification/NotificationList.tsx
  src/notification/NotificationListItem.tsx
  src/notification/NotificationStatus.tsx
  src/post/UpdatePost.tsx
  src/search/Index.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/types/notification.ts
  src/user/UserEdit.tsx
  src/user/UserEditImg.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/UserPostListItem.tsx
  src/user/index.tsx
Labels: 리팩토링

#156 reafactor/auth: 회원가입, 로그인, 유저페이지 수정 입력 정규표현식 수정
  src/auth/Login.tsx
  src/auth/SignUp.tsx
  src/user/UserEdit.tsx
Labels: 피드백 요청, 리팩토링

#165 reafactor: 🔨 email 대문자 입력 방지
  src/auth/Login.tsx
  src/auth/SignUp.tsx
Labels: 리팩토링, 버그 수정

#171 design/all: 미디어 쿼리 break point 상수 정리 및 navbar
  src/Router.tsx
  src/common/Navbar.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 피드백 요청, 스타일

#176 design/all 무한스크롤 기능 구현
  src/InfiniteScroll.tsx
  src/Router.tsx
  src/api/Loading.tsx
  src/common/Spinner.tsx
  src/index.tsx
Labels: 신규 기능

#181 Design/channel media: 헤더, 채널 레이아웃 미디어쿼리 구현
  public/logo.png
  public/logo.svg
  src/Router.tsx
  src/auth/Header.tsx
  src/auth/Logout.tsx
  src/common/Button.tsx
  src/common/Navbar.tsx
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/Navbar.tsx
  src/layout/index.tsx
  src/notification/NotificationStatus.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 스타일

#182 Refactor/search: 모바일로 변경시 검색창 페이지 별도 구현 및 미디어 쿼리 일부 적용
  src/Router.tsx
  src/layout/Channels.tsx
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/SearchBox.tsx
Labels: 리팩토링, 스타일

#183 feature/search: 모바일 검색창 라우터 연결 에러 수정
  src/layout/Navbar.tsx
  src/search/Index.tsx
  src/search/PostList.tsx
Labels: 버그 수정

#188 Design/all layout: 헤더, navBar 레이아웃 수정
  src/Router.tsx
  src/layout/Channels.tsx
  src/layout/Header.tsx
  src/layout/Navbar.tsx
  src/layout/index.tsx
  src/search/PostList.tsx
  src/styles/globalStyle.ts
Labels: 리팩토링, 스타일

#190 Refactor/search: 모바일 버전 페이지네이션 제거 및 검색페이지와 리스트 페이지 이동 시 초기화 문제 해결 등
  src/InfiniteScroll.tsx
  src/Router.tsx
  src/search/Index.tsx
  src/search/PostList.tsx
  src/search/PostListContainer.tsx
  src/search/SearchBox.tsx
Labels: 리팩토링, 스타일

#194 refactor/search: 포스트 타이틀, 베스트 포스트 타이틀, 검색창, 포스트 경과 시간 미디어 쿼리 적용
  src/search/MostLikesPosts.tsx
  src/search/PostList.tsx
  src/search/SearchBox.tsx
Labels: 스타일

#192 Design/user: 유저페이지 모바일 버전 무한 스크롤 추가 및 기타 스타일 수정
  src/hooks/useCheckMobile.ts
  src/hooks/useInfiniteScroll.ts
  src/layout/index.tsx
  src/like/index.tsx
  src/post/DetailPost.tsx
  src/user/FollowListItem.tsx
  src/user/MobileUserPosts.tsx
  src/user/UserFollowers.tsx
  src/user/UserFollowing.tsx
  src/user/index.tsx
Labels: 리팩토링, 스타일

#196 refactor/search: 모바일 버전 글 작성하기 버튼 사라짐 현상 제거
  src/search/PostListContainer.tsx
Labels: 리팩토링

#175 feat: ✨비밀 댓글 기능 임시 구현.
  src/comment/index.tsx
Labels: 피드백 요청, 신규 기능

#197 Refactor/scroll: 스크롤 관련 버그 수정, 상세페이지 이미지 크기 수정
  src/layout/Header.tsx
  src/post/DetailPost.tsx
  src/styles/globalStyle.ts
Labels: 스타일, 버그 수정

#179 reafactor/infifitescroll: infifitescroll hook
  src/api/constValue.ts
  src/hooks/useCheckMobile.ts
  src/hooks/useInfiniteSendQuery.ts
  src/hooks/useIntersectionObserver.ts
Labels: 피드백 요청, 🔥 매운맛, 리팩토링

#185 design/auth: auth 관련 미디어 쿼리 작업
  src/Router.tsx
  src/auth/Header.tsx
  src/auth/Login.tsx
  src/auth/SignUp.tsx
  src/layout/Channels.tsx
  src/layout/index.tsx
Labels: 피드백 요청, 스타일
