Repository prgrms-fe-devcourse/FEDC3_UnsungHero_Donggeun, pull requests merged in 2023-02, with the labels that each got.

#202 feat: og 메타태그 설정
  public/index.html
  public/thumbnail.png
Labels: 신규 기능

#200 Refactor/user post: 수정된 무한스크롤 적용
  src/hooks/useCheckMobile.ts
  src/hooks/useInfiniteScroll.ts
  src/user/MobileUserPosts.tsx
  src/user/UserPostListItem.tsx
Labels: 리팩토링, 버그 수정

#203 fix: 로그인, 회원가입 페이지 라우터 위치 수정
  src/Router.tsx
Labels: 버그 수정

#204 refactor: DetailPost 리팩터링
  src/post/DetailPost.tsx
Labels: 리팩토링
